<?php require  __DIR__ . "../../page-php/header.php"?>


<div class="article">
        <div id="article-content">
                <h1 id="title-1">Mitochondrie, la base du vieillissement</h1>

                <p id="p-1">Voici un ensemble de recherche qui ont pour but d'amélioré nos connaissances sur les mécanismes du vieillissement ainsi qu'illustré les programmes génétiques qui font partie de ce processus ceci va nous permettre de montré l'entropie croissante des organismes. Les mitochondries sont des organites qui intègrent la signalisation cellulaire et le métabolisme pour la réduction du carbone, la production d'ATP, ainsi que de petits messagers et la synthèse de macromolécules en fonction des besoins tissulaire. Le vieillissement se caractérise par une baisse des fonctions mitochondriales, incluent la réduction des enzymes du cycle de krebs (TCA),une baisse de la capacité respiratoire et une augmentation des espèces réactives de l'oxygène (ERO et en anglais: ROS), chez les modèles animaux et humains. Ces altérations peuvent conduire à des mutations de l'ADN, une inflamation et une réduction des fonctions des cellules souches (entrainant une dégradation du tissu produit), la mort cellulaire. L'augmentation des mutations de l'ADN mitochondriale observé chez les mitochondries agées à la fois chez le modèle humain et celui de la souris suggère qu'elles sont à l'origine de l'entropie cellulaire. L'ADN mitochondriale est répliqué par l'ADN polymérase mitochondriale (l'ADN polymérase &gamma;), une expérience a été réalisée en générant un modèle de souris sans l'activité de réparation, afin de permettre la création de mutation dans l'ADN mitochondriale. Ce modèle affiche un phénotype de vieillissement fort, incluant moins de cheveux, des cheveux grisonnant, une cyphose, une activité réduite du complexe respiratoire et une augmentation du stress oxydatif. Le stress oxydatif est considéré comme un déterminant majeur du vieillissement et les mitochondries semble joué un rôle important dans l'apparition et le développement de ces agressions. Pour appuyer cette hypothèse, une baisse en antioxydant pourrait produire un phénotype de souris mutantes à vieillissement cellulaire rapide, pour le vérifier des souris ont subi une carence en enzyme SOD2 (enzyme antioxydante mitochondriale) et elles présentaient un phénotype cutané âgé. Un autre groupe de recherche a démontré que les ROS pourrait ne pas être responsables du vieillissement du phenotype mutant, anisi l'importance du stress oxydatif dans le vieillissement reste contreversé.</p><br><br>
                <h2>Souris mutante (dépletion de l'ADNmt)</h2>
                <p>
                A l'Université d'Alabama, Mr Singh et ses collaborateurs ont décrit une nouvelle souris transgénique avec une dépletion inductible d'ADNmt, c'est à dire un épuisement de l'ADNmt de la souris. Ce modèle porte une modification de l'aspartate en alanine à la position 1135 du gène POLG1 (gène codant la polymérase &gamma;) l'effet délètère au niveau de la protéine est dominant négatif(la mutation provoque une perte totale de fonction, qui n'est pas restaurée par un allèle sauvage) de l'ADN polymérase &gamma;, dont l'expression est sous le contrôle d'un promoteur sensible à la tétracycline. l'administration de doxycycline conduit à l'induction d'ADN polymérase &gamma; mutant qui bloque la réplication de l'ADNmt. Comme l'ADNmt est détruit au moment du renouvellement mitochondriale par mitophagie, l'activation du transgène mène à une réduction de 60% de l'ADNmt après 2 mois. Comme l'ADNmt code les sous-unités de base des complexes respiratoire I, III, IV et F1/F0 ATPsynthase de la mitochondrie, une altération significative de leur activité a été observé. Fait intéressant, le complexe II de la chaine respiratoire, qui est uniquement codé par des gènes nucléaires, présentait également une activité réduite. Au niveau macroscopique l'ADNmt de souris, montre l'accélération du vieillissement attendue, incluent perte de poids et cyphose, mais le vieillissement de la peau était particulièrement sévère et caractérisé par une perte de poils, ces souris affichaient un épiderme hyperkératotique et hyperplastique, une dégradation des follicules de poils et des infiltrations inflamatoires étendus. Bien que le modèle nécessite une caractérisation supplémentaire approfondie, les sections histologique des tissus testés (considéré comme ayant une forte demande d'activité mitochondriale), incluant le foie, le cerveau et le myocarde, n'affichent pas de modification majeure.</p><br><br>
                <h2>Comment les mitochondries mutantes induisent un vieillissement prématuré?</h2>
                <p>
                Savoir comment l'épuisement de l'ADNmt affecte le vieillissement est une question plutôt intéressante. Les infiltrats inflamatoires étendus suggèrent que les mitochondries pourraient produire des ROS, ces dernières pouvant agir en tant que molécule de signalisation pour l'activation de l'inflamasome. Malheureusement l'auteur n'a pas réalisé de mesure du stress oxydatif, mais les cellules dépourvues d'ADNmt sont généralement caractérisées par une diminution de la consomation d'oxygène et par la production de ROS, on peut donc émettre l'hypothèse que le phénotype vieillissant observé ici n'est pas due à un stress oxydatif. Cependant, les deux conséquences majeures suivantes ont été observées dans un modèle cellulaire avec appauvrissement de l'ADNmt en utilisant la même stratégie d'épuisement que celle utilisé chez la souris: &#9312; un réarangement significatif de l'acétylation des histones en raison de modifications indirectes des taux de citrate, &#9313; une réduction de la prolifération cellulaire due à une réduction du potentiel membranaire et à la déstabilisation du facteur induit par l'hypoxie (HIF-1 alpha). Bien que l'on ne comprenne pas clairement le type de réarrangement épigénétique qui se produit pendant le vieillissement, l'épuisement en HIF-1A a conduit à un phénotype de souris avec une accélération du viellissement de la peau. De plus les mitochondries cutanées présentant un appauvrissement de l'ADN affiche une perte de crêtes mitochondriales probablement due à la perte de dimère F1/F0 ATP synthase. En effet, le réarrangement de dimères de l'ATP synthase pourrait prédisposé les cellules à la mort en ouvrant le port de transition de perméabilité (PTP, en anglais PTPC: perméability transition pore complexe). Les auteurs n'ont pas reporté de mesure de la mort cellualire (observé chez la souris mutante); néanmoins, étant donné que plusieurs molécules peuvent agir en tant que motif moléculaire associés aux dégats cellulaires (DAMP), une augmentation de la mort cellulaire induite par les PTPC pourrait provoquer une libération importante de DAMP mitochondriale et donc l'augmentation de l'inflamation.</p><br><br>
                <h2>Récupération suite à une perte d'ADNmt</h2>
                <p>
                Un autre point très intéressant dans cette étude est le rétablissement du phénotype. L'arrêt de l'exposition à la doxycycline a permit une récupération presque complète du contenu en ADNmt et du phénotype cutané après un mois. La récupération en ADNmt est possible car l'ADNmt original n'a pas été complètement épuisé. La récupération du phénotype cutané est plus intriguante. Le modèle de souris mutante a fourni un aperçu important de la façon dont les mitochondries peuvent induire un phénotype vieillissant en affectant les capacités d'auto-renouvellement des cellules souches hématopoïétiques et neurales. Nous supposons que la diminution de la quantité d'ADNmt affecte les fonctions des cellules souches de l'épiderme, menant à un vieillissement de la peau. Pendant longtemps on a pensé que les cellules souches ne dépendaient pas des fonctions mitochondriales (sauf pour la production d'ATP), des observations supplémentaires chez des cellules souches adultes d'autres tissus suggèrent que les mitochondries jouent un rôle fondamentale dans l'auto-renouvellement des cellules souches. Cependant les cellules progénitrices, qui ont une dépendance établie à la respiration mitochondriale dans de nombreux modèles, pourraient être plus sensible à la déplétion de l'ADNmt et donc responsable de la récupération rapide. Souvent, une nouvelle observation soulève de multiples questions. Même si des recherches supplémentaires sont nécessaires, le modèle de souris développé par Singh et ses collègues est un outil extrêmement intéressant pour étudier le vieillissement et le rôle des mitochondries dans l'homéostasie tissulaire.
                </p><br><br>
        </div>
        <?php require_once __DIR__ . "../../article/companion-article.php" ?>
</div>

<?php require_once __DIR__ . "../../page-php/footer.php" ?>